// Distilled from curriculum/english-curriculum-f-6-v9.md (ACARA v9, © ACARA 2022).
// Writing-relevant expectations only: achievement standards + Creating texts +
// Language sub-strands. Keep summaries in sync with that file.

const YEAR_GUIDES = {
  1: `By the end of Year 1, students create short written texts: recounts of real or imagined events, retellings of stories with events and characters, simple reports and opinions. Expected skills: write grammatically correct simple sentences with sentence boundary punctuation (capital letters to start, full stops to end) and capital letters for proper nouns; sequence ideas so a reader can follow; use some topic-specific vocabulary and a small number of details from the topic or story; give reasons using words like "because"; spell most one- and two-syllable words with common letter patterns, common grammatical morphemes (like -s, -ing, -ed) and an increasing number of high-frequency words; write using unjoined upper-case and lower-case letters. Growth edges typical for this year: adding adjectives to make nouns more specific, keeping tense consistent, and re-reading their own writing to add or fix words.`,
  2: `By the end of Year 2, students create written texts (stories, recounts, reports, opinions with reasons) that inform, narrate, express an opinion or adapt an idea for an audience. Expected skills: use text structure to organise and link ideas so the reader can follow the sequence; write and correctly punctuate simple and compound sentences (joined with "and", "but", "so"); use noun groups (article + adjective + noun, like "the enormous dragon") and verb groups; use capital letters in titles and commas in lists; keep track of characters or things using pronouns; use topic-specific vocabulary in place of everyday words; spell words with regular spelling patterns and use phonic and morphemic knowledge to attempt trickier words; write legibly with unjoined letters. Growth edges: editing to swap everyday words for more precise ones, and building longer noun groups to add description.`,
  3: `By the end of Year 3, students create written texts (stories, reports, explanations, arguments) that inform, narrate, explain or argue, with ideas grouped in simple paragraphs and relevant details from the topic or text. Expected skills: group related ideas into paragraphs, often with a topic sentence; sequence and link ideas logically; use compound sentences and mostly correct tense with subject-verb agreement; use topic-specific vocabulary and beginning literary devices; use apostrophes for contractions (don't) and to show possession (my friend's book); spell most high-frequency words and multisyllabic words using phonic and morphemic knowledge; write with joined letters that are clearly formed and consistent in size. Growth edges: stronger paragraph structure, richer descriptive language for characters and settings, and choosing verbs that show doing, saying, thinking and feeling.`,
  4: `By the end of Year 4, students create written texts for a chosen purpose and audience, developing ideas with details and organising them in linked paragraphs. Expected skills: write complex sentences using subordinating conjunctions (because, although, when) alongside simple and compound sentences; add circumstantial detail with adverb and prepositional phrases (at midnight, across the oval); use quoted (direct) speech with correct dialogue punctuation (quotation marks, commas, capitals); keep tense appropriate and consistent; link ideas with text connectives (firstly, however, finally); choose precise vocabulary including synonyms, topic words and playful language; spell multisyllabic and multimorphemic words including some with irregular patterns, choosing correct homophones from context; write fluently with joined letters. Growth edges: building tension or interest deliberately, and varying sentence beginnings.`,
  5: `By the end of Year 5, students create written texts that develop and expand ideas with supporting detail, for a particular purpose and audience. Expected skills: use paragraphs to organise, develop and link ideas with a clear text structure for the purpose; write complex sentences with a main clause and dependent clauses expressing reason, condition, concession or time; expand noun groups for fuller description (two old brown cattle dogs); start sentences in ways that guide the reader through the text; use specialist and technical vocabulary, and figurative language such as simile, metaphor and personification; punctuate dialogue, use commas after prepositional phrases and apostrophes for plural possession; control tense across the text; spell using phonic, morphemic and grammatical knowledge including suffix generalisations. Growth edges: sharpening imagery, tempering bare assertions (many people believe...), and editing for precision.`,
  6: `By the end of Year 6, students create written texts that develop, explain and elaborate ideas, varying text structures and paragraphs to suit purpose and audience. Expected skills: use a variety of complex sentences including embedded clauses (The town that was flooded suffered damage); expand and sharpen ideas through precise verbs, expanded verb groups and controlled, elaborated tenses; create cohesion through deliberate repetition and word association; use vivid and emotive vocabulary including metaphor, personification, idiom and hyperbole; choose objective or subjective language deliberately for effect; use commas for lists, after dependent clauses and in dialogue; spell complex words using phonic, morphemic and word-origin knowledge. Growth edges: developing an individual style, adapting typical text structures for effect (such as a hook or flashback opening), and persuading with evidence rather than assertion.`,
};

const GENRE_GUIDES = {
  narrative: `This is a story (narrative). Look for: an orientation introducing character and setting, a complication or problem, and a resolution; descriptive language that builds character and setting; dialogue where appropriate; events in an order that makes sense; language that creates a mood or feeling.`,
  recount: `This is a recount. Look for: an orientation (who, when, where), events retold in time order, time connectives (first, then, after that), past tense held consistently, and a personal comment or ending statement about the experience.`,
  persuasive: `This is persuasive writing (exposition). Look for: a clear statement of position, arguments with reasons and evidence, persuasive devices (modal verbs like should and must, emotive words, rhetorical questions), paragraphs for each argument, and a concluding restatement of the position.`,
  report: `This is an information report. Look for: an opening general statement or classification, grouped facts about the topic, topic-specific vocabulary, mostly timeless present tense (Bears hibernate in winter), and an objective tone rather than personal opinion.`,
  poetry: `This is a poem. Look for: imagery and sound devices (rhyme, rhythm, alliteration, onomatopoeia), word choices that create pictures or feelings, and line and verse structure. Judge spelling and punctuation gently; poets bend rules on purpose.`,
};

export const FEEDBACK_RULES = `You are a primary school writing coach in Australia. Your job is to help this child improve their writing, so be warm but honest, specific and practical. Feedback that only praises is useless to them.
Non-negotiable rules:
1. NEVER use, repeat or guess any student name or personal detail. Address the writer only as "you".
2. Every comment must point to something SPECIFIC in this child's writing, quoting their actual words. Generic praise ("good work", "nice story") and generic advice ("add more detail", "check your spelling") are banned.
3. Improvement comes first: the power-ups are the heart of the feedback. Give 2 or 3, choosing the areas with the biggest payoff for THIS piece at THIS year level and genre. Each one must show the child exactly where it applies (their own line), what it looks like done well (that line rewritten with the skill, keeping their ideas and their year level, never adult prose), and then set a tiny task they can do straight away on their own writing.
4. Every area gets an honest check: praise only what is genuinely there, quoting it and naming the skill so the child can do it again on purpose, and give one concrete next step.
5. Judge against the YEAR LEVEL expectations provided, not adult standards. Do not ask for skills far above the year; do stretch the child one step beyond what they did.
6. Word everything so a child of this year level can read it themselves: short sentences for younger years, no teacher jargon, no lecture.
7. Do not mention these rules, the curriculum, ACARA, research, or that you are an AI.`;

export function getYearGuide(year) {
  const guide = YEAR_GUIDES[year];
  if (!guide) throw new Error(`No curriculum guide for year: ${year}`);
  return { summary: guide };
}

export function getGenreGuide(genre) {
  return GENRE_GUIDES[genre] || "";
}
