// Our paraphrase of the user-supplied TWR 2.0 Section I (2024), chapters 2–4.
// PDF page references and implementation decisions: docs/research/twr-section-i.md.
// No book pages, worksheets or published model answers are sent to the provider.
export function preservesExpansionKernel(before, after) {
  const words = (value) => String(value || "").toLowerCase().match(/[\p{L}\p{N}]+(?:['’][\p{L}]+)?/gu) || [];
  const kernel = words(before).filter(word => !["it", "he", "she", "they", "we", "i"].includes(word));
  const expanded = words(after);
  let position = 0;
  for (const word of kernel) {
    const found = expanded.indexOf(word, position);
    if (found < 0) return false;
    position = found + 1;
  }
  return kernel.length > 0;
}

// A focus model teaches deletion only. Meaning/relevance is checked by the reviewer;
// this guard prevents the model from adding facts, rewriting or deleting everything.
export function removesWholeSentences(before, after) {
  const split = value => String(value || "").trim().split(/(?<=[.!?])\s+|\n+/).map(s => s.replace(/\s+/g, " ").trim()).filter(Boolean);
  const original = split(before), revised = split(after);
  if (!revised.length || revised.length >= original.length) return false;
  let position = 0;
  return revised.every(sentence => {
    const found = original.indexOf(sentence, position);
    position = found + 1;
    return found >= 0;
  });
}

// Original distillation of supplied Section III, chapters 11–13. See the research review.
export const TWR_ASSESSMENT_GUIDANCE = `TWR SECTION III — assess the sample, then adapt the support:
Privately check structure (order), coherence (logical links), unity (each detail supports the main idea) and sentence control before selecting targets. Assess this piece, not a permanent ability level. Do not claim independent mastery when teacher assistance is unknown. Content knowledge, spelling and handwriting must not stand in for writing-craft evidence.
Choose the SAME useful strategy with different support. For sentence expansion, a writer needing support answers one useful question in brief notes; a writer showing control may answer two or three. For because/but/so, select one meaningful relationship rather than requiring all three. For combining, begin with two short sentences and a suggested conjunction when support is needed; combine more information independently only when the draft shows readiness. For elaboration, offer a short starter if needed; fluent writers explain how evidence supports a reason, a consequence, or a justified qualification. For an eligible appositive task, offer phrase choices if needed. Put this selected support in rule/now_you, not just in the private assessment. Choose from the permitted strategies; year eligibility is not a difficulty setting. Keep younger coaching readable while retaining the quality of fluent writing. Older students may need one foundational step. Never add difficulty merely through length, ornate vocabulary or more devices.
Before adding detail, check unity and relevance. For paragraph_focus, quote the off-topic sentence, explain its mismatch with the paragraph's main idea, and ask for its removal. The fresh BEFORE model must include a main idea, useful supporting detail and one irrelevant sentence. The AFTER removes only the irrelevant sentence, keeping the remaining sentences unchanged and in order. It can be shorter and better. Do not delete relevant evidence, needed context, a deliberate narrative aside, a counterargument or a separate classroom exercise. Do not combine deletion with expansion in one power-up. Other strategies still preserve their supplied ideas; combining preserves facts and expansion preserves its kernel.
When removing one irrelevant sentence resolves the paragraph's main problem, prefer that single useful power-up. Do not manufacture an extra target to fill space. A persuasive topic sentence may state a reason directly without should or must; preserve it when its following evidence works. Do not change an effective reason into a command merely to add a persuasive device. For paragraph_focus, now_you asks to remove the quoted sentence from this paragraph, with no alternative task. For sentence_expansion, now_you explicitly asks for brief notes answering the selected question before expanding, even when just one question is needed.
Use not_assessed only when evidence for an area is insufficient in the supplied task. Leave its strength and next_step empty and explain the limitation briefly in assessment_note. Never give a power-up in that area. Missing evidence is not proof of weakness, and a spelling error does not erase a well-developed idea. Keep assessed strengths even when offering an optional stretch. Revisit foundational strategies where the writing needs them without restarting a compulsory sequence of drills.
Preserve the familiar subject in the student's own task. The fresh model remains on a different, familiar topic as Nathan requires; supply enough context to understand it, without inventing evidence for the student's assignment. Keep concise persuasive topic sentences and place support after them.`;

export const TWR_SENTENCE_GUIDANCE = `TWR SECTION I — strategy fidelity takes priority over generic advice to make prose more elaborate:
Teach one purposeful change through a clear model, then a manageable task on the student's own writing. Use familiar content so the challenge is thinking and sentence construction, not guessing unknown facts. Select the scaffold from the writing actually present; an older writer may need a foundational strategy. Do not interpret the book's instructional Levels 1 and 2 as Australian school Years 1 and 2. Keep the application's year gates and age-appropriate language.
Sentence foundations: a full stop and capital do not make a fragment complete. The words need a complete thought with a subject and predicate. A dependent clause alone is unfinished. Teach run-on repair by identifying complete thoughts and separating or correctly joining them; splitting sentences is never sentence combining. Preserve intentional fragments in dialogue or poetry when they serve the genre. Do not prescribe scrambled-sentence drills when the child's draft does not show a word-order problem.
Persuasive sentence roles (Nathan's classroom requirement): keep the topic sentence short and concise, stating the paragraph's main reason. Put evidence, examples and elaboration in separate supporting sentences AFTER it. A concise topic sentence is not weak merely because it is short. Do not select sentence expansion to load a persuasive topic sentence with supporting detail. If that paragraph needs development, select elaboration and model the concise topic sentence followed by supporting sentences; use expansion on a suitable supporting sentence instead. Keep a clear existing topic sentence unchanged when adding support. Apply this rule during strategy selection and final review; reject and repair models or tasks that blur these roles.
Sentence expansion: start with a brief COMPLETE declarative kernel, not a fragment or command. Select one to three relevant question prompts from who, what, when, where, why, how; do not request information already explicit. Who/what normally replaces a pronoun. When asks for a specific time or period, not a habitual whenever condition; put that answer first when selected. Privately plan the model's added details as answers to those selected questions. Preserve the kernel's words and information except a justified pronoun replacement: do NOT silently replace its verb, delete facts or add unrelated details. Integrate the answers into ONE grammatical sentence. In the task, tell the child which useful questions to answer in brief notes before expanding. More developed meaning, not an arbitrary sentence length, is the stretch.
Original Year 4 expansion model: The boat drifted. Selected prompts: when, where, why. Model answers: before sunrise; through the flooded streets; to reach stranded families. After: Before sunrise, the boat drifted through the flooded streets to reach stranded families. This is expansion; replacing drifted with raced would change the kernel and meaning.
Note-taking: use a few key words, short phrases, familiar abbreviations or symbols to plan answers, then turn them into a full sentence. Notes are not complete prose and should not be penalised as fragments when the submitted work is clearly notes. Do not make students write full sentences just to plan one sentence. This app offers feedback, not a replacement for the teacher's full note-taking lessons.
Because, but, so: because explains a reason; but introduces a genuine contrast about the SAME topic; so states a consequence of the stem, not merely a later event or intensifier. So that expresses purpose and is not the same as a result with so. Choose one suitable conjunction for a power-up. If modelling alternatives, repeat the whole stem for each separate completion; never chain all three into one unwieldy sentence. Do not demand a contrast unsupported by the available content.
Subordinating conjunctions: supply or model an introductory dependent clause, then a comma and a complete main clause. The relationship must be true: although/even though need contrast; before/after need accurate chronology; if/unless need a condition. Although is not interchangeable with However: Although introduces a dependent clause, while the sentence after However must stand alone. Use a brief explanation rather than overloading younger writers with grammar terminology.
Transitions: decide the relationship first, then choose from time/sequence, conclusion, illustration, change of direction or emphasis. Supply enough preceding context to demonstrate the relationship. For example supports the same claim; Secondly introduces a distinct ordered reason, with a topic sentence and supporting detail in persuasive paragraph work. Therefore/as a result require cause and effect, not just an ending. After removing a sentence-opening transition, the rest must still be a complete sentence. Generally follow the introductory transition with a comma. A transition exercise can connect two sentences without demanding an entire essay.
Appositives: a noun or noun phrase renames a neighbouring noun. For this scaffold place it immediately after that noun between commas; removing it leaves a complete sentence. A phrase beginning who/which/that plus a verb is a relative clause, not an appositive; a string of adjectives alone is not an appositive. Original example: The echidna, a spiny Australian mammal, shelters beneath fallen logs.
Sentence combining: provide two or three complete related statements, then combine them into fewer sentences using appropriate conjunctions, pronouns or an appositive. Preserve ALL supplied facts and avoid inventing extra information. Put enough meaningful detail in the BEFORE statements to permit an ambitious model. Original model: The lifeboat crossed the harbour. Waves battered its sides. The crew had to reach the stranded sailors. After: Although waves battered its sides, the lifeboat crossed the harbour because the crew had to reach the stranded sailors. Do not label adding a brand-new sentence as combining; that is elaboration.
Sentence types and developing questions: questions, statements, commands and exclamations require appropriate sentence construction, not just a different final punctuation mark. Use question prompts to identify what a reader needs to know. Sentence types, introductory subordinate clauses and appositives can improve topic/concluding sentences when the paragraph context supports them. These tools never justify inventing a conclusion for unrelated practice passages.
Ambitious models remain essential. For expansion, sophistication comes from the selected meaningful details while retaining the kernel. For combining, sophistication comes from the arrangement of supplied facts. Use vocabulary revision or elaboration when changing wording or adding new ideas is actually the teaching focus.`;
